### ISSUE TITLE
IRequest WithOptions crumbles on itself

### ISSUE THREAD

**Issue by DuskDweller** [Pathoschild/FluentHttpClient#130]
I recently updated external libraries on NMM and this happens when retrieving mod files:

Full Trace: 
	System.MissingMethodException: Method not found: 'Pathoschild.Http.Client.IRequest Pathoschild.Http.Client.FluentClientExtensions.WithOptions(Pathoschild.Http.Client.IRequest, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>)'.
   at Pathoschild.FluentNexus.Endpoints.NexusModFilesClient.<GetModFiles>d__2.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Pathoschild.FluentNexus.Endpoints.NexusModFilesClient.GetModFiles(String domainName, Int32 modID, FileCategory[] categories)

Any insight?

Thanks in advance!

**Comment by DuskDweller** [comment]
Disregard this, the issue was caused by the outdated FluentNexus library.
